### PR TITLE
license & CI updates

### PR DESCRIPTION
**Pull request by till**
(Accidentally merged #43)

### CODE REVIEW

**Comment by till** [comment]
@Mischosch @four43 @cezum — Either of you has "significant" contributions on this repository, are you okay with the change in license?

**Comment by till** [comment]
Sorry — @ghost — I think your changes got committed by proxy (through @four43). Anyway, let me know if either of you has objections to moving to Apache 2.0 (from MIT).

**Comment by Mischosch** [comment]
reading this: https://www.quora.com/Whats-the-different-between-Apache-v2-0-and-MIT-license?share=1 - would prefer MIT, but I'm ok with that change, as I don't work/use it now and the package will not really needed anymore (ZF1)

**Comment by four43** [comment]
I've been fortunate enough to move away from the PHP stack for most projects. I no longer use this library.

**Comment by till** [comment]
@four43 I guess that means you are okay with changing this license? Please state. ;)

**Comment by four43** [comment]
Yeah go ahead and change it @till, do what you have to do man! Apache 2.0 is cool over here. Thanks for the effort into this library, it sure was helpful when we were using it.

**Pull request merged**
