### PR TITLE
Bootstrap3

### PR DESCRIPTION
**Pull request by peterslivka**
Partial updates for Bootstrap3 compatibility

### CODE REVIEW

**Comment by Mischosch** [comment]
@till as this lib is under EasyBib namespace - is there anything speaking against Bootstrap v3 support for it from your side?

@peterslivka are you able to fix at least the tests? Is this PR finished from your side? Will need to test with a real form setup before I would merge it…

**Comment by till** [comment]
No, :+1: great idea!

**Comment by peterslivka** [comment]
I can try to take a look onto tests but I'm pretty busy right now, so it could take me a few weeks or even months until I find some time...

**Comment by till** [comment]
@peterslivka it seems that one of your changes introduced a bug — "Call to undefined function.". Effectively can't merge with this bug/build failure there.

Btw, I just pushed some travis-ci/dev setup improvements in #42. Might be good to merge master into your branches.

Let me know if you need any help.

**Pull request closed without merging**
